### ISSUE TITLE
KeyboardResize => false not working on Android

### ISSUE THREAD

**Issue by yigitbacakoglu** [ionic-team/cordova-plugin-ionic-keyboard#8] opened 2018-04-10 06:46 UTC
I added `<preference name="KeyboardResize" value="false" />` into my config.xml and it works well with IOS but not works with Android-24

As I see, it adds padding-bottom to the scroll-content class.

AVD Details

  ```
  Name: Nexus_5X_API_24
  Device: Nexus 5X (Google)
    Path: /Users/usr/.android/avd/Nexus_5X_API_24.avd
  Target: Google Play (Google Inc.)
          Based on: Android 7.0 (Nougat) Tag/ABI: google_apis_playstore/x86
    Skin: nexus_5x
  Sdcard: 100M

```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v9.5.0
    npm   : 5.6.0 
    OS    : macOS Sierra
    Xcode : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by Spartanace1024** [comment] 2018-04-13 16:54
@olivermuc I went ahead and tried to implement what you said for Android and couldn't get it to work. Any chance I could be doing something wrong? I kept getting android unbound error. 

After doing some additional research it looked like that <edit config> tag only applies to plugin.xml for cordova. See [here](http://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config).

Thanks in advance!

**Comment by olivermuc** [comment] 2018-04-13 17:04
Make sure to add the android name space to the widget tag, top of config.xml.
See [here](https://github.com/dpa99c/cordova-custom-config/issues/24#issuecomment-172981002)

**Comment by Spartanace1024** [comment] 2018-04-13 17:05
@olivermuc just writing up a response figuring that out :) Thanks so much for the help!

**Comment by zfalen** [comment] 2018-05-03 00:51
I also am experiencing an Android-only situation. 

It looks like the `'keyboardDidShow' `and `'keyboardWillHide'` (and presumably the other two) are not firing when the Android keyboard is active or leaving.

 I've got the "adjustPan" fix working, but I need to be able to _scroll_ while the keyboard is open to access an element lower down. On iOS, I was able to use the two events above to add / remove CSS that leverages the `'keyboardHeight'` value to do this. However, I'm getting no luck on the Android emulator. 

Device: Pixel 2
Android Version: 8.1.0

**Comment by viking2917** [comment] 2018-09-28 21:30
@olivermuc genius tip, thank you! @mlynch I am using keyboard 2.1.3 and I still see the behavior that the Android keyboard is resizing things, I can't confirm it's fixed. It's on a quite complicated app however so not simple to reproduce; that said, @olivermuc 's workaround did correct the resizing...

**Comment by mlynch** [comment] 2018-09-28 22:08
Thanks for the info, will re-open for now

**Comment by alex-steinberg** [comment] 2018-12-05 19:16
> Outside of the event handling and passing back the keyboard height, Android is defacto not supported in the way iOS is by this plugin.
> 
> Dear devs, it would have helped (me as well) to point out that KeyboardResize and KeyboardResizeMode are **iOS only** relevant.
> 
> It would also tremendously help to document a generic (cross platform) keyboard popup/content space handling approach for **Ionic v2+ & WKWebView**.
> 
> At this point what I have gathered, is that you need to essentially turn of any plugin based screen resizing (as it's not cross platform) and instead implement app logic to listen to keyboard events and modify bottom-padding (to push up content) of the screen thats overlayed by the keyboard.
> 
> Other observations:
> For iOS, **KeyboardResizeMode = native** doesn't seem to change the view height, but adding a new height to the html tag.
> 
> For Android (& cordova v6.4+) you can add to config.xml:
> 
> ```
>  <platform name="android">
>         <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application/activity">
>             <activity android:windowSoftInputMode="adjustPan" />
>         </edit-config>
> ```
> "adjustPan" will put the keyboard onto of your content, "adjustResize" will shrink the view (the real view, not just the html element).

This works well when adding the platform but, on each subsequent prepare, it removes key plugin `intent-filter` tags inside the `<activity android:name="MainActivity" ...` tag. Any ideas?

**Comment by ayyazzafar** [comment] 2019-02-20 15:53
@olivermuc Thank you so much. Only yours solution worked perfectly. I really appreciate.

**Comment by testappbk2000** [comment] 2019-06-03 20:56
I think Ionic is waste of time ? Please reply  ?

**Comment by an-manish** [comment] 2019-08-12 14:54
> Outside of the event handling and passing back the keyboard height, Android is defacto not supported in the way iOS is by this plugin.
> 
> Dear devs, it would have helped (me as well) to point out that KeyboardResize and KeyboardResizeMode are **iOS only** relevant.
> 
> It would also tremendously help to document a generic (cross platform) keyboard popup/content space handling approach for **Ionic v2+ & WKWebView**.
> 
> At this point what I have gathered, is that you need to essentially turn of any plugin based screen resizing (as it's not cross platform) and instead implement app logic to listen to keyboard events and modify bottom-padding (to push up content) of the screen thats overlayed by the keyboard.
> 
> Other observations:
> For iOS, **KeyboardResizeMode = native** doesn't seem to change the view height, but adding a new height to the html tag.
> 
> For Android (& cordova v6.4+) you can add to config.xml:
> 
> ```
>  <platform name="android">
>         <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application/activity">
>             <activity android:windowSoftInputMode="adjustPan" />
>         </edit-config>
> ```
> 
> "adjustPan" will put the keyboard onto of your content, "adjustResize" will shrink the view (the real view, not just the html element).

* I had solved this issue by modifying default behaviour as "adjustResize" to "adjustPan" and it was working great with ionic v3.
``` But in ionic v4 when we use same method to modify AndroidManifest.xml it's not even allowing to scroll forms (Like everything freezed). Any guide please.```

**Comment by jcesarmobile** [comment] 2019-08-21 15:43
Closing as this can't be implemented in Android.
The only option is doing what some people have proposed about the `windowSoftInputMode` in the AndroidManifest.xml by using `edit-config` or `config-file` tags.
But I've documented which method as for iOS and which ones are for Android. They also warn when using them in the unsupported platforms.

**Closed by jcesarmobile** 2019-08-21 15:43 UTC

**Comment by tuananh1998hust** [comment] 2020-02-20 04:36
> Outside of the event handling and passing back the keyboard height, Android is defacto not supported in the way iOS is by this plugin.
> 
> Dear devs, it would have helped (me as well) to point out that KeyboardResize and KeyboardResizeMode are **iOS only** relevant.
> 
> It would also tremendously help to document a generic (cross platform) keyboard popup/content space handling approach for **Ionic v2+ & WKWebView**.
> 
> At this point what I have gathered, is that you need to essentially turn of any plugin based screen resizing (as it's not cross platform) and instead implement app logic to listen to keyboard events and modify bottom-padding (to push up content) of the screen thats overlayed by the keyboard.
> 
> Other observations:
> For iOS, **KeyboardResizeMode = native** doesn't seem to change the view height, but adding a new height to the html tag.
> 
> For Android (& cordova v6.4+) you can add to config.xml:
> 
> ```
>  <platform name="android">
>         <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application/activity">
>             <activity android:windowSoftInputMode="adjustPan" />
>         </edit-config>
> ```
> 
> "adjustPan" will put the keyboard onto of your content, "adjustResize" will shrink the view (the real view, not just the html element).

edit-config-file can not change adjustResize to adjustPan
how i can fix it ?

**Comment by alex-steinberg** [comment] 2020-02-20 06:32
I did this by using a Cordova hook to manually edit the AndroidManifest.xml.

**Comment by hanoj-budime** [comment] 2020-03-16 11:32
for ios ?? @alex-steinberg

**Comment by alex-steinberg** [comment] 2020-03-16 11:35
@HanojHanu `<preference name="KeyboardResize" value="false" />`
