### ISSUE TITLE
Ionic Tabs pushed up above keyboard

### ISSUE THREAD

**Issue by ChrisPearce** [ionic-team/cordova-plugin-ionic-keyboard#25] opened 2018-06-12 00:18 UTC
When bringing up the keyboard, the ion-tabs control is getting pushed up and is displayed immediately above the keyboard.

n.b. This problem is not occurring when using the now deprecated keyboard located at https://github.com/ionic-team/ionic-plugin-keyboard.

**Comment by cyptus** [comment] 2018-06-15 14:36
got the same issue. disableScroll method is not available in this plugin - any solutions?!

**Comment by sfaizanh** [comment] 2018-06-16 07:53
Hide/Show Tabs when keyboard is opening/closing

**Comment by chrene** [comment] 2018-06-19 09:09
@ChrisPearce 
https://github.com/ionic-team/cordova-plugin-ionic-keyboard#preferences

setting KeyboardResize false fixed this for me
<preference name="KeyboardResize" value="false" />

**Comment by radulescuandrew** [comment] 2018-08-02 09:16
Set **windowSoftInputMode** to **adjustPan** in AndroidManifest.xml

You can use this hook:
`
#!/usr/bin/env node
var fs = require('fs');
var path = require('path');

var pathToManifest = path.join(__dirname, '../platforms/android/app/src/main', 'AndroidManifest.xml');
if(fs.existsSync(pathToManifest)) {
    var config = fs.readFileSync(pathToManifest, 'utf8');

    var result = config.replace(/(android:windowSoftInputMode=").*?(")/, '$1adjustPan$2');
    fs.writeFileSync(pathToManifest, result, 'utf8');
}
`

**Comment by mathewk2017** [comment] 2018-09-04 09:35
@radulescuandrew if we Set **windowSoftInputMode** to **adjustPan** , other pages which does not have tabs wont scroll.
I have a form which will fill the entire screen. When I changed the value to adjustPan.keyboard overlay the fields.

**Comment by jcesarmobile** [comment] 2019-01-30 17:05
I can't reproduce with latest Ionic and latest keyboard

**Closed by jcesarmobile** 2019-01-30 17:05 UTC
