### ISSUE TITLE
Navbar gets hidden

### ISSUE THREAD

**Issue by MartinCarlson** [ionic-team/cordova-plugin-ionic-keyboard#48] opened 2018-10-09 19:12 UTC
I have the latest plugin and when the keyboard pops up everything pushes up including the navbar.

The navbar should remain static and only the content below should scroll and resize with the keyboard.  Anyone know of a preference that I am missing to achieve this? 

Older versions of this plugin had a option "this.keyboard.disableScroll(true)" which prevented the navbar being hidden but that caused another issue whereby the footer that contains the input being entered into from being hidden behind the keyboard.

The behavior I am after is that they keyboard appears, the view resizes/scrolls BUT NOT the header/navbar.

**Comment by startupfoundry** [comment] 2018-10-12 00:45
Having the same issue.

**Comment by yryuu** [comment] 2018-10-18 01:36
config.xml add
<preference name="HideKeyboardFormAccessoryBar" value="true" />

**Comment by yryuu** [comment] 2018-10-18 01:42
`
<preference name="HideKeyboardFormAccessoryBar" value="false" />
`

**Comment by MartinCarlson** [comment] 2018-10-18 11:44
> HideKeyboardFormAccessoryBar

Does nothing for me, keyboard pops up and navbar still jumps off screen.

**Comment by startupfoundry** [comment] 2018-10-22 20:10
> `<preference name="HideKeyboardFormAccessoryBar" value="false" />`

This is already in my config as well. Navbar still has the same issue.

**Comment by wing505** [comment] 2018-11-02 01:37
Having the same issue.

**Comment by terminaltor** [comment] 2018-11-13 15:02
Same here...

**Comment by tribalboy3000** [comment] 2018-12-03 13:53
Any updates? I have this issue as well.

**Comment by Sh1n1x** [comment] 2019-01-07 19:08
four month later.... And this issue already here, good job ionic team !!!!

**Comment by startupfoundry** [comment] 2019-01-07 19:21
There have been issues related to keyboard/navbar/auto height/auto scroll, going back to Ionic 2 (a couple years) without resolution. Unfortunately, we had to rewrite in React Native as these sort of issue makes building a good chat application impossible in Ionic. 

Really unfortunate as the rest of Ionic was **exactly** what we were looking for, but we couldn't end up shipping what we built as this issue is a production roadblock. Sad to have to change frameworks when the rest of Ionic is so good (especially now that we can build without cordova) 😞.

**Comment by 7thsonch** [comment] 2019-01-25 21:17
Same issue here while it only happens on android, not ios.
Already tried to add
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application/activity">
  <activity windowSoftInputMode="adjustPan" />
</edit-config>
```
to config.xml as suggested in a forum post. Still no success :(

**Comment by m1aw** [comment] 2019-02-15 12:02
This is honestly very annoying and makes and it's making us consider alternatives to Ionic our next apps, mostly because of the lack of answers and concern from the Ionic Team.

**Comment by m1aw** [comment] 2019-02-15 18:32
Well, our problem apparently was a bit different. I ended up debbuging the plugin on iOS and realized it wasn't being called because `ionic-plugin-keyboard` was still installed after we upgraded to `cordova-plugin-ionic-webview`, ended up removing the plugin and rebuilding platforms, and it's working now. 

```
ionic cordova plugin remove ionic-plugin-keyboard
ionic cordova platform remove ios
ionic cordova platform add ios
```

**Comment by pedrovitor074** [comment] 2019-02-18 20:00
did someone find a way to solve this? i still with this issue

**Comment by tiandongmao** [comment] 2019-04-29 06:05
In order to be compatible with ios 10, I have to use UIWebView
<preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />

Then I encountered this problem. After search and try for a period, I solved it as follows:

1. Remove cordova-plugin-ionic-keyboard, then install ionic-plugin-keyboard.
cordova plugin remove cordova-plugin-ionic-keyboard
cordova plugin add ionic-plugin-keyboard

2. Disable auto scroll.
platform.ready().then(() => {
  cordova.plugins.Keyboard.disableScroll(true);
  .......
});

3. Modify the style of ion-app with javascript code, when keyboard show and hide. 
Reference to another issue, replied by @JoeMeeks:
https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/53#issuecomment-484644608

if can not work, We need to add settimeout somewhere.
setTimeout(() => {
  if (self.ionapp) {
         self.ionapp.setAttribute('style', 'height: calc(100% - ' + e.keyboardHeight + 'px);');
   }
}, 100);

Thanks for @JoeMeeks

**Comment by jcesarmobile** [comment] 2019-08-21 17:14
I can't reproduce with latest version of the plugin on Ionic 4 apps.

Can any of you provide a sample app?

Also make sure you don't have the old ionic-plugin-keyboard as it causes conflicts as some people have stated.

**Comment by MartinN71** [comment] 2019-11-01 16:07
Removing the ionic-plugin-keyboard worked for me (ionic 3 app)

**Comment by jcesarmobile** [comment] 2019-11-01 16:14
going to close since I can't reproduce and nobody answered after 2 months and MartinN71 says it got fixed by uninstalling ionic-plugin-keyboard

**Closed by jcesarmobile** 2019-11-01 16:14 UTC
Labels: needs reply
