### ISSUE TITLE
Support for '@ionic-native/keyboard'

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/cordova-plugin-ionic-keyboard#14] opened 2018-04-24 20:49 UTC
Is the the plugin for the wrapper of '@ionic-native/keyboard'? 

Or does it only work with the deprecated repo https://github.com/ionic-team/ionic-plugin-keyboard as it points to in the doc: https://ionicframework.com/docs/native/keyboard/

If that's true - why wouldn't the plugin wrapper point to the latest/supported cordova plugin?

**Comment by MichelKansou** [comment] 2018-04-26 15:26
Having the same issue here why is the main repo is deprecated and `@ionic-native/keyboard` is not supported ?

**Comment by jaybloke** [comment] 2018-05-16 23:14
This is the deal dealbreaker for me... I reverted back to the deprecated keyboard as this is so poorly documented it's almost unbelievable.

**Comment by jacquesdev** [comment] 2018-05-22 16:12
@mlynch

**Comment by mlynch** [comment] 2018-05-22 17:08
Duplicate of #9

**Closed by mlynch** 2018-05-22 17:08 UTC
