### ISSUE TITLE
addEventListener not working

### ISSUE THREAD

**Issue by Calvin1121** [ionic-team/cordova-plugin-ionic-keyboard#93] opened 2019-06-15 14:59 UTC
I wanna get the keyboard's height to fixed the input above the keyboard; but I used these codes, they are not working~
window.addEventListener('keyboardDidShow', e => {}) and window.addEventListener('native.keyboardshow',e =>{}) ;
The code works fine in Ionic3 but not working in Ionic4. (the attachment)
please help me. thx~
![屏幕快照 2019-06-14 下午7 15 03](https://user-images.githubusercontent.com/31435496/59552990-36a8c100-8fc1-11e9-824f-2f3349eb2604.png)

**Comment by jcesarmobile** [comment] 2019-06-19 11:56
this should work
```
window.addEventListener('keyboardDidShow', (event) => {
    // Describe your logic which will be run each time when keyboard is about to be shown.
    console.log(event.keyboardHeight);
});
```

Can you provide a sample app using it that doesn't work?

**Comment by jcesarmobile** [comment] 2019-08-21 18:09
Closing as I can't reproduce and no sample app was provided.

**Closed by jcesarmobile** 2019-08-21 18:09 UTC
