### ISSUE TITLE
keyboard implimentation

### ISSUE THREAD

**Issue by akkariyassine** [ionic-team/cordova-plugin-ionic-keyboard#76] opened 2019-03-06 08:37 UTC
hello , i try to use keyboard plugin , i installed it ut when i use keyboard.show this error lunched
![sans titre](https://user-images.githubusercontent.com/46689927/53867146-7f7cd100-3ff3-11e9-9d95-71e1936236a9.png)

**Comment by jcesarmobile** [comment] 2019-03-06 12:23
Can you provide more information about how are you using the plugin or a sample project?

**Comment by akkariyassine** [comment] 2019-03-06 12:33
i use it like the documentation said, imort the plugin in the provides of
app. modules and use in in a component (keyboard. show) but there no error
or result nothing happens


Le mer. 6 mars 2019 à 13:23, jcesarmobile <notifications@github.com> a
écrit :

**Comment by jcesarmobile** [comment] 2019-03-06 12:55
Can you at least link the documentation?
And if using Ionic, also provide the Ionic version

**Comment by jcesarmobile** [comment] 2019-04-08 17:08
Closing as I can't reproduce and the requested information was not provided

**Closed by jcesarmobile** 2019-04-08 17:08 UTC
