### ISSUE TITLE
White space above keyboard

### ISSUE THREAD

**Issue by haveamission** [ionic-team/cordova-plugin-ionic-keyboard#96] opened 2019-06-24 20:15 UTC
I am noticing that there is some white space above the keyboard at all points on iOS.

There is no white space underneath my div (above keyboard) before the keyboard fires.

**Comment by JensWinkler69** [comment] 2019-06-27 11:36
Same issue here. Works fine if I try it with the Ionic Dev App (On Device)

But after building it with Xcode on the device, the white space appears. 
![IMG_0012](https://user-images.githubusercontent.com/52282608/60263297-94ea7380-98e0-11e9-8989-67b5c9d93513.jpg)

**Comment by haveamission** [comment] 2019-06-27 14:58
So a partial solution I've found for my use-case is that it seems to be related to VH.

I set my div for my input to have top: 87vh or so, and that seems to do the job, though imperfectly.

I suspect it's related to vh due to this though

**Comment by Mapiac** [comment] 2019-06-27 22:56
Also see this.  AdjustPan maybe?

**Comment by haveamission** [comment] 2019-06-28 13:41
Can you use AdjustPan with iOS? All the examples I am seeing are with Android

**Comment by haveamission** [comment] 2019-06-30 13:15
Ok, I have a better solution ultimately.

Give your input div a set height (in my case, 5em).

Set top to calc(100vh - 5em)

Works perfectly. Add a minor transition speed to make it look more natural.

**Comment by diegodotta** [comment] 2019-08-06 00:18
Have you tried 
<preference name="KeyboardResizeMode" value="body" /> or 
<div keyboard-attach>?

Kind of solve some weird interface issues here.

**Comment by jcesarmobile** [comment] 2019-08-22 14:53
Closing as I can't reproduce and looks like it was a CSS issue. 
If you think it's not really fixed, please, create a new issue and provide more information, with a sample app where it can easily reproduced.

**Closed by jcesarmobile** 2019-08-22 14:53 UTC
