### ISSUE TITLE
disableScrollingInShrinkView not working?

### ISSUE THREAD

**Issue by trinitiwowka** [ionic-team/cordova-plugin-ionic-keyboard#24] opened 2018-06-05 11:27 UTC
on platform Android keyboard overflow view.

WEB: http://joxi.ru/a2XnYXgU10gP3r
Android: http://joxi.ru/1A5GJo0Un0JMZm

**Comment by mlynch** [comment] 2018-06-07 15:14
Can you describe the issue more? Not sure what to look at. Thanks

**Comment by jcesarmobile** [comment] 2019-08-21 16:08
closing as there was no answer and it's not clear what the issue is.

**Closed by jcesarmobile** 2019-08-21 16:08 UTC
