### ISSUE TITLE
ios accessory bar is not showing 

### ISSUE THREAD

**Issue by gaurav-chandra** [ionic-team/cordova-plugin-ionic-keyboard#70] opened 2019-02-12 11:32 UTC
```
Keyboard.hideFormAccessoryBar(null, (currentValue) => { console.log(currentValue); });
```
or
```
Keyboard.hideFormAccessoryBar(false);
```
does not show the accessory bar on ios

using ionic v4 stable

**Comment by jcesarmobile** [comment] 2019-02-28 18:41
Can you provide a sample app?
I can't reproduce
You have to call it while the keyboard is hidden, doesn't take effect if you run it while it's displayed, if it is displayed it will appear next time you open the keyboard.

**Comment by gaurav-chandra** [comment] 2019-03-01 04:58
plain ionic 4 hello world. I am writing this in app.component.ts:

```
 this.platform.ready().then(() => {
            if (window.cordova) {
              Keyboard.hideFormAccessoryBar(null, (currentValue) => { console.log(currentValue); });
            }
}
```

**Comment by jcesarmobile** [comment] 2019-03-01 07:15
That jus return true or false, doesn’t set the value

**Comment by gaurav-chandra** [comment] 2019-03-01 07:20
At first I did: ```Keyboard.hideFormAccessoryBar(false);``` Since, it did not show the accessory bar, I resorted to the above code. Which does not give me any result. I will tinker more and will post the result here. Thanks for the help.

**Comment by jcesarmobile** [comment] 2019-03-01 10:11
And what type of input/field do you use to show the keyboard?

**Comment by Razorholt** [comment] 2019-03-04 06:18
Make sure the following preference in your config.xml file is set properly:
<preference name="HideKeyboardFormAccessoryBar" value="false"/>

Although technically designed for Blackberry phones, it does hide the Accessory Bar ( including the done button)  in iOS.

**Comment by novemberstorm** [comment] 2019-03-14 21:46
Still can't get this to work for me, any idea?

**Comment by jcesarmobile** [comment] 2019-04-08 17:08
Closing as I can't reproduce and the requested information was not provided

**Closed by jcesarmobile** 2019-04-08 17:08 UTC
